services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - ./mongo_db/:/data/db/
